
- name: Importing (free) key
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

- name: Importing (non-free) key
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

- name: Enable RPM Fusion - nonfree-updates
  tags:
    rpm-fusion-non-free
  copy:
    content: |-
      [rpmfusion-nonfree-updates]
      name=RPM Fusion for Fedora $releasever - Nonfree - Updates
      #baseurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
      enabled=1
      enabled_metadata=1
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-updates-debuginfo]
      name=RPM Fusion for Fedora $releasever - Nonfree - Updates Debug
      #baseurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-debug-$releasever&arch=$basearch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

      [rpmfusion-nonfree-updates-source]
      name=RPM Fusion for Fedora $releasever - Nonfree - Updates Source
      #baseurl=http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-source-$releasever&arch=$basearch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    dest: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
    mode: 0644 

- name: Enable RPM Fusion repository and upgrade codecs - free-updates
  tags:
    rpm-fusion
  copy:
    content: |-
      [rpmfusion-free-updates]
      name=RPM Fusion for Fedora $releasever - Free - Updates
      #baseurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
      enabled=1
      enabled_metadata=1
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever      

      [rpmfusion-free-updates-debuginfo]
      name=RPM Fusion for Fedora $releasever - Free - Updates Debug
      #baseurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-debug-$releasever&arch=$basearch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever      

      [rpmfusion-free-updates-source]
      name=RPM Fusion for Fedora $releasever - Free - Updates Source
      #baseurl=http://download1.rpmfusion.org/free/fedora/updates/$releasever/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-source-$releasever&arch=$basearch
      enabled=0
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    dest: /etc/yum.repos.d/rpmfusion-free-updates.repo
    mode: 0644 


- name: Enable RPM Fusion repository and upgrade codecs - nonfree
  tags:
    rpm-fusion
  copy:
    content: |-
      [rpmfusion-nonfree]
      name=RPM Fusion for Fedora $releasever - Nonfree
      #baseurl=http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/os/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
      enabled=1
      enabled_metadata=1
      metadata_expire=14d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever      #
      [rpmfusion-nonfree-debuginfo]
      name=RPM Fusion for Fedora $releasever - Nonfree - Debug
      #baseurl=http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-debug-$releasever&arch=$basearch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever      #
      [rpmfusion-nonfree-source]
      name=RPM Fusion for Fedora $releasever - Nonfree - Source
      #baseurl=http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/source/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-source-$releasever&arch=$basearch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    dest: /etc/yum.repos.d/rpmfusion-nonfree.repo
    mode: 0644    #
- name: Enable RPM Fusion free updates
  tags:
    rpm-fusion-free
  copy:
    content: |-
      [rpmfusion-free]
      name=RPM Fusion for Fedora $releasever - Free
      #baseurl=http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
      enabled=1
      metadata_expire=14d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever      #
      [rpmfusion-free-debuginfo]
      name=RPM Fusion for Fedora $releasever - Free - Debug
      #baseurl=http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/debug/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-debug-$releasever&arch=$basearch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever      #
      [rpmfusion-free-source]
      name=RPM Fusion for Fedora $releasever - Free - Source
      #baseurl=http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/source/SRPMS/
      metalink=https://mirrors.rpmfusion.org/metalink?repo=free-fedora-source-$releasever&arch=$basearch
      enabled=0
      metadata_expire=7d
      type=rpm-md
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    dest: /etc/yum.repos.d/rpmfusion-free.repo
    mode: 0644    

- name: Configure Visual Studio Code repository
  copy:
    content: |-
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/vscode.repo
    mode: 0644

- name: Add Docker Repo
  copy:
    content: |-
      [docker-ce-stable]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-stable-debuginfo]
      name=Docker CE Stable - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/debug-$basearch/stable
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-stable-source]
      name=Docker CE Stable - Sources
      baseurl=https://download.docker.com/linux/fedora/$releasever/source/stable
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-test]
      name=Docker CE Test - $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-test-debuginfo]
      name=Docker CE Test - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/debug-$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-test-source]
      name=Docker CE Test - Sources
      baseurl=https://download.docker.com/linux/fedora/$releasever/source/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-nightly]
      name=Docker CE Nightly - $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-nightly-debuginfo]
      name=Docker CE Nightly - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/debug-$basearch/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg      

      [docker-ce-nightly-source]
      name=Docker CE Nightly - Sources
      baseurl=https://download.docker.com/linux/fedora/$releasever/source/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: Add Hashcorp Repo
  copy:
    content: |-
      [hashicorp]
      name=Hashicorp Stable - $basearch
      baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://rpm.releases.hashicorp.com/gpg      

      [hashicorp-test]
      name=Hashicorp Test - $basearch
      baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://rpm.releases.hashicorp.com/gpg
    dest: /etc/yum.repos.d/hashcorp.repo
    mode: 0644

- name: Add kopia Repo
  copy:
    content: |-
      [Kopia]
      name=Kopia
      baseurl=http://packages.kopia.io/rpm/stable/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://kopia.io/signing-key
    dest: /etc/yum.repos.d/kopia.repo
    mode: 0644

- name: Add Microsoft Repo
  copy:
    content: |-
      [packages-microsoft-com-prod]
      name=packages-microsoft-com-prod
      baseurl=https://packages.microsoft.com/fedora/38/prod/
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/yum.repos.d/microsoft.repo
    mode: 0644

- name: Add zsh-completions Repo
  copy:
    content: |-
      [shells_zsh-users_zsh-completions]
      name=zsh-completions (Fedora_Rawhide)
      type=rpm-md
      baseurl=https://download.opensuse.org/repositories/shells:/zsh-users:/zsh-completions/Fedora_Rawhide/
      gpgcheck=1
      gpgkey=https://download.opensuse.org/repositories/shells:/zsh-users:/zsh-completions/Fedora_Rawhide/repodata/repomd.xml.key
      enabled=1
    dest: /etc/yum.repos.d/zsh-completions.repo
    mode: 0644

- name: Add Teams Repo
  copy:
    content: |-
      [teams-for-linux]
      name=Repo for the unofficial Teams for Linux package
      baseurl=https://repo.teamsforlinux.de/rpm/
      enabled=1
      gpgcheck=1
    dest: /etc/yum.repos.d/teams.repo
    mode: 0644 

- name: Add Chrome Repo
  copy:
    content: |-
      [google-chrome]
      name=google-chrome
      baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64
      enabled=1
      gpgcheck=1
      gpgkey=https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/yum.repos.d/chrome.repo
    mode: 0644     